---
# Storage
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fortio-data-class
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: fortio-data-pv
spec:
  storageClassName: fortio-data-class
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/istio/fortio"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fortio-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: fortio-data-class
---
